### ISSUE TITLE
Settings button doesn't work

### ISSUE THREAD

**Issue by Dostoi** [mofosyne/tagdrop#3]
The settings button doesn't do anything with the version 1.0 on a alcatel one touch pop 2 with android 4.4

**Comment by mofosyne** [comment]
oh, yea its not ment to be there, I haven't coded in any settings page.

But does everything else work for you? Can you scan from zxing and see the running man?

**Comment by mofosyne** [comment]
Removed as of V1.3 . Readme section added instead.

**Comment by Dostoi** [comment]
The version 1.2 is working fine with me
I find the 1.2 interface more user friendly than the first one. I read about that, just being able to delete a scan would be perfect if you make a mistake ^^
